### PR TITLE
[feature] list commands for both attachment and emojis

### LINKED ISSUE #2118: [feature] emojis are not included in admin media commands
### Describe the bug with a clear and concise description of what the bug is.

When I run `gotosocial admin media list-local` my custom emojis are not listed at all. The same seems to happen with `gotosocial admin media list-remote`. This can be a problem for people performing backups using these commands.

### What's your GoToSocial Version?

v0.11.0-rc3

### GoToSocial Arch

arm64

### What happened?

_No response_

### What you expected to happen?

_No response_

### How to reproduce it?

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by rdelaage**
# Description

This pull request adds commands to list both attachment and emojis.

closes #2118 

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by tsmethurst** [comment]
Hiya! Sorry to keep you waiting, we've been trying to fix bugs from 0.11.0 so haven't been doing much reviewing of new PRs lately. I think in this case it's not so easy to add tests for our CLI tooling, so don't worry about it for now.

Would it be OK with you if I pushed a couple changes to your branch to fix the linter and make some small documentation changes?

**Comment by daenney** [comment]
I took a look at this, and there's two things that we might want to consider:

* We're using media (can be either singular or plural) and emojis (plural), but then attachment (singular). We should be consistent here and since we expect more than 1, I think attachment**s** is the way to go
* The commands themselves are becoming a bit of a mouthful, "admin media list attachments remote" etc. I'm not sure what to do about that but I wonder if we should structure that differently

**Comment by tsmethurst** [comment]
Hey @daenney and @rdelaage !

I pushed a couple commits to this branch to reduce the long command paths, and updated documentation for it. Lmk what you think :)

**Review by daenney — APPROVED** [review]

**Comment by tsmethurst** [comment]
> Looks good to me, great work! The behavior for remote media changed, URL was returned before and local path are shown now. Could it be a problem?

Ah thanks, didn't realize that was the case. I wonder why we were ever returning remote URL :thinking: 

In any case, I think it makes more sense to return the storage path. We'll just have to remember to put a note about this when we release with this feature!

**Comment by daenney** [comment]
> Looks good to me, great work! The behavior for remote media changed, URL was returned before and local path are shown now. Could it be a problem?

Good point. I think that's a good change actually. There's not a ton of point to knowing the remote URL, since if you want to do anything with that image it's probably deleting the locally cached copy, or using it as an exclusion list for backups. Not quite sure why I decided to return the URL originally for remote media.

**Pull request merged**
