### PR TITLE
[chore] add migration to drop tables status_to_emojis and account_to_emojis

### LINKED ISSUE #1075: [chore] Remove unused m2m tables `status_to_emojis` and `account_to_emojis`
Since https://github.com/superseriousbusiness/gotosocial/pull/1073 and https://github.com/superseriousbusiness/gotosocial/pull/1074 we don't use those tables for selecting via bun's relations API anymore, so we should be able to just drop the tables.

### PR DESCRIPTION
**Pull request by voigt**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

This pull request implements a db migration to drop the tables `status_to_emojis` and `account_to_emojis`.

closes #1075

## Checklist

Please see ticket #1075 for remarks.

- [X] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [X] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [X] I/we have performed a self-review of added code.
- [X] I/we have written code that is legible and maintainable by others.
- [X] I/we have commented the added code, particularly in hard-to-understand areas.
- [X] I/we have made any necessary changes to documentation.
- [X] I/we have added tests that cover new code.
- [X] I/we have run tests and they pass locally with the changes.
- [X] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by NyaaaWhatsUpDoc** [comment]
As well as the tables themselves, there's also some code that will need to be dropped to prevent issues: anywhere that is using `gtsmodel.StatusToEmoji{}` or `gtsmodel.AccountToEmoji{}`

**Comment by NyaaaWhatsUpDoc** [comment]
> Yeah, there is even more as documented here: [#1075 (comment)](https://github.com/superseriousbusiness/gotosocial/issues/1075#issuecomment-1347947850)
> 
> If you agree, I rome those code paths as well. @NyaaaWhatsUpDoc

These are good to delete:
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/status.go#L300
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/emoji.go#L81
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/account.go#L195
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/account.go#L228

For these, you'll just need to remove the bun struct tag I'm pretty sure:
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/gtsmodel/status.go#L40 (btw. what is m2m?)
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/gtsmodel/account.go#L45

I'm not _exactly_ sure what `m2m` means maybe @tsmethurst can fill in on that

**Comment by tsmethurst** [comment]
> I'm not exactly sure what m2m means maybe @tsmethurst can fill in on that

many-to-many :) It's a type of relation, like one to many, many to one

**Comment by voigt** [comment]
Having a look into the failing tests...

**Comment by voigt** [comment]
Just little update on this PR: I got sick in the meantime and was not able to finish this. Hope that I'll find time in the coming days!

**Comment by tsmethurst** [comment]
No rush, hope you feel better soon!

**Comment by NyaaaWhatsUpDoc** [comment]
Hey hows it going @voigt ? Feeling any better?

If you're still not feeling too great let us know and one of us can take over if you'd like :)

**Comment by tsmethurst** [comment]
Heya, I'm gonna close this for now, but let us know if you want to reopen it again, it's no problem :)

**Pull request closed without merging**
