### PR TITLE
[feature] Implement `/api/v1/instance/peers` endpoint

### PR DESCRIPTION
**Pull request by tsmethurst**
This PR implements the `api/v1/instance/peers` endpoint, and closes https://github.com/superseriousbusiness/gotosocial/issues/650

By default, neither open nor suspended peers are exposed to unauthenticated users via the API. This PR also adds some new config options to allow admins to expose these endpoints if they desire.

If no query parameters are provided to the endpoint, then a mastodon-api compatible 'flat' list of open peers will be returned, to maintain compatibility.

If query parameters are provided, then a more informative, structured object will be returned.

---

Example responses:

`/api/v1/instance/peers`

```json
[
  "example.org",
  "fossbros-anonymous.io"
]
```

`/api/v1/instance/peers?filter=suspended`

```json
[
  {
    "domain": "replyguys.com",
    "suspended_at": "2020-05-13T13:29:12.000Z",
    "public_comment": "reply-guying to tech posts"
  }
]
```

`/api/v1/instance/peers?filter=suspended,open` -- with more domains and obfuscation

```json
[
  {
    "domain": "example.org"
  },
  {
    "domain": "fossbros-anonymous.io"
  },
  {
    "domain": "o*g.*u**.t**.*or*t.*r**ev**",
    "suspended_at": "2021-06-09T10:34:55.000Z",
    "public_comment": "just absolutely the worst, wowza"
  },
  {
    "domain": "replyguys.com",
    "suspended_at": "2020-05-13T13:29:12.000Z",
    "public_comment": "reply-guying to tech posts"
  }
]
```

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
It's incompatible with what other implementations have been using for this output, right?

**Comment by tsmethurst** [comment]
> It's incompatible with what other implementations have been using for this API endpoint, right?

Unfortunately yes, because we provide a list of objects instead of a list of strings, but I also think that makes it more useful overall. If this was an integral part of the API we'd stick more closely to what mastodon does so as not to break compatibility, but I'm not sure what services or clients actually use that endpoint when talking to mastodon. Do you know?

**Comment by ClearlyClaire** [comment]
I don't have a definite list, but as far as I know, pretty much all fediverse crawlers providing stats on number of users and software usage rely on this endpoint.

**Comment by ClearlyClaire** [comment]
IIRC some projects use some nodeinfo endpoint to expose that kind of information.

**Comment by tsmethurst** [comment]
> IIRC some projects use some nodeinfo endpoint to expose that kind of information.

Ah okay! Well we do still have the standard nodeinfo endpoint (discoverable via well-known), and the /api/v1/instance endpoint. As long as no client apps rely on /api/v1/instance/peers specifically for core functionality then I think we should be okay :)

**Comment by tsmethurst** [comment]
Updated this PR following @f0x52 's suggestions. Now, for no query params, a mastodon-compatible 'flat' string array will be returned. When query params are provided, a domain object is returned instead. This allows us to provide more info to callers while still maintaining masto api compatibility.

**Pull request merged**
