### PR TITLE
Fix 410 Gone race on account deletes

### LINKED ISSUE #1313: [bug] 400 errors on delete requests
### Describe the bug with a clear and concise description of what the bug is.

ActivityPub user delete messages cause 400 errors due to trying to webfinger the deleted user. Example request:

```
POST /users/sentynel/inbox HTTP/1.0
Host: social.sentynel.com
Connection: upgrade
X-Forwarded-For: REMOVED
X-Forwarded-Proto: https
Content-Length: 771
User-Agent: http.rb/5.1.0 (Mastodon/4.0.2; +https://mastodonapp.uk/)
Date: Thu, 05 Jan 2023 23:17:09 GMT
Accept-Encoding: gzip
Digest: SHA-256=wZOpZiEzBCDDrJ+WVQmzjsjfjsPd+N7gBn2ymmDrw6k=
Content-Type: application/activity+json
Signature: keyId="https://mastodonapp.uk/users/REMOVED#main-key",algorithm="rsa-sha256",headers="(request-target) host date digest content-type",signature="REMOVED"

{"@context":"https://www.w3.org/ns/activitystreams","id":"https://mastodonapp.uk/users/REMOVED#delete","type":"Delete","actor":"https://mastodonapp.uk/users/REMOVED","to":["https://www.w3.org/ns/activitystreams#Public"],"object":"https://mastodonapp.uk/users/REMOVED","signature":{"type":"RsaSignature2017","creator":"https://mastodonapp.uk/users/REMOVED#main-key","created":"2023-01-05T23:16:58Z","signatureValue":"REMOVED"}}
```

Error response (note also that this is contained in the HTML error template, but should probably be the JSON one for the API?).
```
1Bad Request: couldn't get requesting account https://mastodonapp.uk/users/REMOVED: item could not be retrieved: GetRemoteAccount: error while fingering: fingerRemoteAccount: error fingering @REMOVED@mastodonapp.uk: GET request to https://mastodonapp.uk/.well-known/webfinger?resource=acct:REMOVED@mastodonapp.uk failed (410): 410 Gone
```

We probably still need to do this request to verify the user is actually gone (since we can't check the message signature unless we already have their key), but 410 is the expected result.

### What's your GoToSocial Version?

v0.6.0

### GoToSocial Arch

_No response_

### Browser version

_No response_

### What happened?

_No response_

### What you expected to happen?

_No response_

### How to reproduce it?

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Sentynel**
# Description

This handles a case where a 410 Gone could occur at an unexpected place in the processing of account deletion requests for accounts we were previously unaware of.

This is currently running on my live GTS instance, though the actual race hasn't yet happened so I can't strictly prove it's working yet.

closes #1313 for real

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by tsmethurst** [comment]
Hell yeah, nice one! Will review rn :)

**Comment by tsmethurst** [comment]
This seems like a good solution. Is there any risk we might end up not processing the delete correctly, but still return 202 to the caller?

**Comment by Sentynel** [comment]
I don't believe so - if you look in `GetAccountByURI()` https://github.com/superseriousbusiness/gotosocial/blob/main/internal/federation/dereferencing/account.go#L63-L82, you can see that errors in `enrichAccount()` are non-fatal in the case that we already have the account in the database (it just falls back to using the one it already had and swallows the error). It's only in the case we didn't have the account already that failure to look it up is fatal. Therefore, we can only get a 410 Gone at this point in the code if we didn't already have the account in the database, and doing nothing is therefore safe.

**Comment by tsmethurst** [comment]
Brilliant, thank you! Will merge before 0.7.0 so we can include this fix then :) Much appreciated

**Comment by NyaaaWhatsUpDoc** [comment]
Nice fix! Well caught :)

**Pull request merged**
