### PR TITLE
Add Alpine Linux to third party packages

### PR DESCRIPTION
**Pull request by raspbeguy**
# Description

I added a link to Alpine Linux GtS package.

## Checklist

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tsmethurst** [comment]
Thanks! Could you add this one as well? https://archlinux.org/packages/extra/x86_64/gotosocial/

Apparently there's a GtS package in both the community and extra repositories, so we may as well mention them both :)

**Comment by daenney** [comment]
> Thanks! Could you add this one as well? https://archlinux.org/packages/extra/x86_64/gotosocial/
> 
> Apparently there's a GtS package in both the community and extra repositories, so we may as well mention them both :)

Community doesn't exist anymore in Arch. It got combined with Extra during the svn-to-git migration 2 weeks ago. We should remove the community link as that'll start getting outdated and only have the Extra one.

**Comment by tsmethurst** [comment]
Ahh okay thanks @daenney! In that case @raspbeguy could you replace the link with https://archlinux.org/packages/extra/x86_64/gotosocial/ ? Then I'll merge this :)

**Comment by tsmethurst** [comment]
Hey @raspbeguy sorry to mess you about, but it looks like https://github.com/superseriousbusiness/gotosocial/pull/1859 is an easier solution because it requires less manual maintenance of version links and stuff. So I'm gonna close this one, but thank you for drawing attention to it, and please feel free to open other PRs in the future!

**Pull request closed without merging**
