### PR TITLE
Switch markdown from blackfriday to goldmark

### LINKED ISSUE #1240: [bug] ASCII hearts get removed from markdown posts </3
### Describe the bug with a clear and concise description of what the bug is.

Including either `<3` or `</3` in markdown posts causes strange behavior.

### What's your GoToSocial Version?

v0.6.0

### GoToSocial Arch

armv7 Binary

### Browser version

_No response_

### What happened?

Input text:
```md
hello <3 old friend <3 i loved u </3 :(( you stole my heart
```

Content HTML:
```html
<p>hello old friend i loved u
```

Note that the closing `</p>` tag is missing, not just the latter half of the sentence.

To summarize:
- `<3` is removed
- `</3` is removed along with everything following it, including the closing `</p>` tag.

### What you expected to happen?

Expected HTML:
```html
<p>hello &lt;3 old friend &lt;3 i loved u &lt;/3 :(( you stole my heart</p>
```

Taken from the [CommonMark dingus](https://spec.commonmark.org/dingus/) :)

### How to reproduce it?

Provide input as above.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by autumnull**
# Description

This pull request fixes certain markdown rendering issues by changing the rendering backend from blackfriday to [goldmark](https://github.com/yuin/goldmark).

Closes #1240

## Checklist

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [x] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by tsmethurst** [comment]
This looks great!! @blackle and @illfygli do you have any comments? Tagging you both because you've worked in these parts of the code :)

**Comment by blackle** [comment]
looks pretty good! I can't remember the issue I fixed, but I did add a test case for it. If all the tests are still passing, then I'm good with it.

**Comment by illfygli** [comment]
Looks good and cool, this is what I was wishing for on matrix when I did the hashtag stuff!

**Comment by autumnull** [comment]
@blackle i think ur talking about #783 and yeah it still passes! because of the fact that i made dedicated inline parsers for hashtags and mentions so they only get converted where any other inline markdown would be valid (i.e. not in code blocks).

there's also #789 which this PR doesn't fix. but i'll comment more on that issue itself if this gets merged cos i have notes.

**Comment by igalic** [comment]
how does this new markdown library deal with handles of the form: `@_foo_@example.com`?

**Comment by autumnull** [comment]
@igalic mentions and hashtags now have dedicated inline parsers, so any underscores appearing in hashtags or mentions cannot be interpreted by any other inline parser. they're parsed on a first-seen basis, so once the `@` sign is seen then it catches everything up until the end of the mention.

**Pull request merged**
