### PR TITLE
introduce development settings and config validation

### PR DESCRIPTION
**Pull request by ForestJohnson**

### CODE REVIEW

**Comment by ForestJohnson** [comment]
Just dawned on me I didn't test this at all

**Comment by ForestJohnson** [comment]
The tests are throwing this locally for me, I have no idea why: `db teardown: db was nil`

**Comment by tsmethurst** [comment]
Hey @ForestJohnson , do you feel like picking this one up again for #495 ?

**Comment by tsmethurst** [comment]
Since we have https://github.com/superseriousbusiness/gotosocial/pull/562 I'm gonna close this one now. Thank you for the work though! Since I borrowed some of the logic you implemented in this PR in the linked PR, i gave you credit there <3

**Pull request closed without merging**
