### PR TITLE
[feature] Rain Forest Theme

### PR DESCRIPTION
**Pull request by xmgz**
:sloth: I missed a green-ish theme to select from **default** options

From wikipedia **sloth**:

> tree sloths spend most of their lives hanging upside down in the trees of the tropical rainforests

A life worth living, if you ask me.

So searched online for some *rain forest color palette* to inspire this GtS theme.

* gradient background as it gets darker when you go deep in the forest (aka scroll down in the TL)
* some sun light spots pass through the high trees ceiling (yellow/orange bits)
* `code`and `quote` styled just to make it more  distinct from regular posts and relate to other elements like wood/water/earth
* language mark styled (I know most of you do not set other than english, but many of us take advantage of Fediverse's language settings)
* polls unchanged.

I think all sections have good contrast ratio, also increased visibility in user profile section.

Seriously considered top header border with solid white color as would make it better for most header pictures, but wanted to keep the *sunny* tint

You can test with **custom css** section or just creating a `sweet-home.css` file in ./web/assets/theme/` folder, restart *gotosocial* and select from *user* control panel.

Or you can [preview it here](https://gts.xmgz.eu/@ghose)

Enjoy! and please consider to add this or any variation of green theme. **Thank you**.

## Edit

I did not commit minor latest changes as published in https://github.com/superseriousbusiness/gotosocial/pull/3021#issuecomment-2176006239

### CODE REVIEW

**Comment by NyaaaWhatsUpDoc** [comment]
oh this is a wonderful theme / PR, thank you! though i'm gonna leave actual review of this to @tsmethurst who knows CSS / has more colour-based opinions than i

**Comment by xmgz** [comment]
thank you @NyaaaWhatsUpDoc :hugs: 

:facepalm: 

**forgot to commit** latest minor changes before making PR (but already in the «preview»)

```
/* wood/earth colors */
  --codebg: #3A2722;  /* darker caoba */
  --quotebg: #800000; /* maroon */
/* water */
  --fg-reduced: #BBEBFF;
```

and retired the «border» in stats

these are minor changes to reflect water/wood/earth... used in user stats, post's data and stats, bio background. I would later add it



I will make a new PR

**Comment by tsmethurst** [comment]
This looks nice, thanks for doing it ^_^

The only issue I can see so far is that the text + background on the "Show More" button doesn't meet WCAG contrast standards. Normally when writing a new theme I do it in firefox and periodically use the "accessibility" tab in the console to check for contrast issues. If you can fix that, and add the other changes you wanted to do, this will be mergeable I think :)

Btw, you might also consider styling polls in the same vein as the rest of the theme, but not a big deal :P

**Comment by xmgz** [comment]
I hate github BTW :sweat_smile:   

excuse me if I eventually have moved around some files/folders, I've tried my best to bring here version 1.0 with latest changes.

**Comment by tsmethurst** [comment]
Thanks for this!

**Pull request merged**
