### PR TITLE
[chore] expose statuses table row count to prometheus

### PR DESCRIPTION
**Pull request by machiel**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

I have exposed a new Prometheus Gauge, that tracks the amount of statuses in the statuses table.

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [ ] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [x] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

I have not discussed these changes before implementing them, but since the work is already done it might just be easier to discuss whether or not this change is desirable in this MR itself. Hope that's okay.

### CODE REVIEW

**Comment by machiel** [comment]
Perhaps, instead of exposing this gauge, I could rely on something like https://github.com/albertodonato/query-exporter. Adding a guage like this will possibly lead to a rabbit hole of more and more metrics requiring exposure, and thus more code and maintenance.

**Comment by tsmethurst** [comment]
Mm. I'll hold off on this one until after we've released 0.14.0, and then we can maybe have a discussion about what metrics it's sensible to expose, and come up with some kind of schema for doing so. I'm worried if folks keep adding metrics here and there without some kind of overarching plan, it might become a bit messy.

**Comment by daenney** [comment]
The statuses table itself will grow over time, as you federate with things. In and of itself, it's not a metric you can act on. Is it good if it's 0, small, or huge?

We do report the number of local statuses as a metric, as that can tell an operator something about how the instance is used, peak posting times for local users etc. This can be useful to schedule maintenance activity around, help identify a performance issue during active times etc.

I don't think we should be exposing "number of records in a table" metrics, or generic database metrics, through GoToSocial. The query-exporter is a good one if that's of interest to someone.

**Comment by machiel** [comment]
Thanks, that makes sense - closing PR.

**Pull request closed without merging**
