### PR TITLE
Update Apache docs to use 127.0.0.1 instead of localhost

### PR DESCRIPTION
**Pull request by EchedeyLR**
# Description

Update Apache docs to use 127.0.0.1 instead of localhost as done with Nginx at #1264.

## Checklist

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I we have performed a self-review of added code.
- [x] I we have written code that is legible and maintainable by others.
- [x] I we have commented the added code, particularly in hard-to-understand areas.
- [x] I we have made any necessary changes to documentation.

### CODE REVIEW

**Review by igalic — CHANGES_REQUESTED** [review]
thanks! here's some feedback

**Comment by igalic** [comment]
> thanks! here's some feedback

Well that didn't work

**Comment by EchedeyLR** [comment]
Did I make something wrong? I cannot see the proposed changes.

**Review by igalic — APPROVED** [review]
after rereading your patch, and [the documentation](https://httpd.apache.org/docs/2.4/rewrite/), I've come to the conclusion that there's nothing to improve on here!

**Comment by tsmethurst** [comment]
Thanks for this :)

**Pull request merged**
