### PR TITLE
[chore] Bump tooling versions, bump go -> v1.23.0

### PR DESCRIPTION
**Pull request by tsmethurst**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

This pull request bumps the following:

- go v1.22 -> v1.23
- golangci-lint v1.57.2 -> v1.62.0 (and gosec linting)
- alpine v3.19.1 ->  v3.20
- gotosocial-drone-build v0.6.0 -> v0.7.0, which includes:
  - docker buildx v0.11.2 -> v0.16.2
  - goreleaser v1.25.1 -> v2.3.2

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [ ] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [ ] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Review by daenney — APPROVED** [review]

**Comment by tsmethurst** [comment]
Looks like a deprecation notice to address in `goreleaser`:

> DEPRECATED:  snapshot.name_template  should not be used anymore, check https://goreleaser.com/deprecations#snapshotnametemplate for more info

I'll address that tomorrow or so.

**Comment by tsmethurst** [comment]
Hmm this is now blocked on go-swagger, which gives the following error under go v1.23.0:

`panic: WARNING: can't determine refined type any (*types.Alias)`

**Comment by NyaaaWhatsUpDoc** [comment]
not really sure what we're gonna do about this :thinking: 

there does seem to be [this PR](https://github.com/go-swagger/go-swagger/pull/3137) which *fixes* things, but it depends whether we use type aliases as to whether this change will effect us or not... i might try a build with it and see if it changes anything

**Comment by NyaaaWhatsUpDoc** [comment]
okay running go-swagger with https://github.com/go-swagger/go-swagger/pull/3137 doesn't cause any changes with our build. i'm going to make a temporary release for us with this fix so we can at least bump to Go 1.23

**Pull request merged**
