### PR TITLE
Add documentation for log directory creation

### PR DESCRIPTION
**Pull request by sargant**
See #1023

### CODE REVIEW

**Comment by NyaaaWhatsUpDoc** [comment]
Looks good, though should created log directory have permissions `0700` ?

**Comment by sargant** [comment]
True - maybe changing the log path to /var/log/gotosocial.log would be better? Then permissions aren't an issue and there's no additional manual user instructions. Don't want to be moving log file targets unexpectedly though.

**Comment by tsmethurst** [comment]
Oh... I think it's likely that it was meant to be in `log` rather than `logs` originally, and this was an error... Feel free to change the path imo, for consistency

**Comment by sargant** [comment]
OK - there's an alternative PR in !1030 that changes the default log path instead and leaves the documentation unchanged

**Comment by tsmethurst** [comment]
Thank you! I merged the other PR so i'll close this one now :)

**Pull request closed without merging**
