### PR TITLE
Indicate that media and video sizes are also for download

### PR DESCRIPTION
**Pull request by EchedeyLR**
Explicitly tell that video and image size are for both upload and download.

### CODE REVIEW

**Comment by EchedeyLR** [comment]
I recently realized by a conversation with @foreverxml what it seems the mix between upload and download sizes for image and video in the settings as well as its clarification in documentation.

I guess, that similar to what it happens with emojis, this should be changed to local and remote settings to provide wider configuration.

This pull request is made with the guess that it is really like this.

**Comment by tsmethurst** [comment]
IIRC it isn't the case that `media-image-max-size` and `media-video-max-size` also limit what your instance will download. The maximum fetchable body size is hardcoded right now to 40MB (https://github.com/superseriousbusiness/gotosocial/blob/main/internal/httpclient/client.go#L108-L111), but I don't believe we limit the size of downloaded attachments beyond that. Unless i'm missing something. Which is very possible because it's been a while since I poked at this part of the codebase :')

**Comment by EchedeyLR** [comment]
Could we leave this pull request open for discussion or similar about it?

To be exact, I was confused about it when I first spoke to @foreverxml as they had a problem getting higher files than this if I remember correctly.

However, I opened this being unsure. Maybe things could get worked to create a variable that is specific for download?

**Comment by tsmethurst** [comment]
> Maybe things could get worked to create a variable that is specific for download?

that's a good idea :)

**Comment by tsmethurst** [comment]
Heya, I opened https://github.com/superseriousbusiness/gotosocial/issues/1029 so we can discuss this there rather than leaving the PR open :)

**Pull request closed without merging**
