### PR TITLE
[bugfix]: Fix IPv6 validation

### PR DESCRIPTION
**Pull request by daenney**
The current code considers ff00::/8 valid, but contrary to the comment that's not the global unicast range. ff-prefixes in IPv6 denote multicast.

This adapts the code to take the same approach as IPv4, explicitly blacklisting reserved internal/private ranges.

### CODE REVIEW

**Comment by daenney** [comment]
An alternative would be to whitelist the allocated ranges from https://www.iana.org/assignments/ipv6-unicast-address-assignments/ipv6-unicast-address-assignments.xhtml instead.

**Comment by daenney** [comment]
If I'm reading the code right and seeing how this is always used through Sanitize on outgoing requests, then I think most outgoing communication with IPv6-enabled instances might be failing.

**Comment by tsmethurst** [comment]
I will defer to @NyaaaWhatsUpDoc on this one since she authored the sanitize code :)

**Comment by daenney** [comment]
I double-checked this in the Go Playground with an IPv6 address of one of my boxes: https://go.dev/play/p/X-VMfnKuQkT.

That results in `false`, whereas it's very much a valid IPv6 unicast address.

**Comment by NyaaaWhatsUpDoc** [comment]
Yes that is very much an oops on my behalf :')

**Comment by daenney** [comment]
Thanks for checking and merging this so fast!

**Pull request merged**
