### PR TITLE
[frontend] colorscheme redesign, some other small css tweaks

### PR DESCRIPTION
**Pull request by f0x52**
Still kind of a work in progress, trying to pick a better color palette, and to document how those can be combined to maintain predictable contrast ratios.

image
image
image
image
 
Needs some more checking, especially with HTML/Markdown formatted posts I think

### CODE REVIEW

**Comment by tsmethurst** [comment]
Excited about this one :eyes:

**Comment by tsmethurst** [comment]
I had a read through! Looks good so far. Some things that come to mind:

With the new unexpanded status layout, what happens if someone has a really long display name? does it smush into the date? And what do unexpanded statuses with show more / show less buttons look like?

For color variable names, instead of `white`, `gray`, `orange`, and `blue`, perhaps they could be foreground, background, accent, and trim, or something like that? Then it'll be less confusing if someone wants to change their foreground color to black and background to white, etc. Whaddya think?

**Comment by f0x52** [comment]
> With the new unexpanded status layout, what happens if someone has a really long display name? does it smush into the date? And what do unexpanded statuses with show more / show less buttons look like?

Needs a bit of a fix still, but we can cut off the displayname with an ellipsis. Was also thinking it might be nice to have a smaller date format (with relative times), so then it takes up less space too.

> For color variable names, instead of `white`, `gray`, `orange`, and `blue`, perhaps they could be foreground, background, accent, and trim, or something like that? Then it'll be less confusing if someone wants to change their foreground color to black and background to white, etc. Whaddya think?

I'm considering adding a bit more proxy variables for that, we kind of already do, with colors, names for colors, specific locations that use those names.
so
```
$orange1: blah;
$accent: $orange1;
$avatar-border: $accent;
```

**Comment by tsmethurst** [comment]
> it might be nice to have a smaller date format (with relative times), so then it takes up less space too.

I think this works better in clients than it does via a web UI, but we could definitely shorten the date format a bit in other ways (maybe just show like `10/09/22 - 13:36` or something?).

I'd say more proxy variables aren't necessarily required (though it's fine if so); imo the important thing is to just not name variables after certain colors, because it makes it more confusing when users/admins wanna write custom css in the future, if you get me

**Comment by f0x52** [comment]
> I think relative time works better in clients than it does via a web UI, but we could definitely shorten the date format a bit in other ways (maybe just show like `10/09/22 - 13:36` or something?).
Yeah that'd help, maybe also shortening it to just the time if it's the same day?

> I'd say more proxy variables aren't necessarily required (though it's fine if so); imo the important thing is to just not name variables after certain colors, because it makes it more confusing when users/admins wanna write custom css in the future, if you get me
Fair, that does make it easier/more logical to change a shade everywhere in one change

**Comment by tsmethurst** [comment]
> Yeah that'd help, maybe also shortening it to just the time if it's the same day?

Sure :) That's a good idea

**Comment by f0x52** [comment]
This PR is kind of tangled with https://github.com/superseriousbusiness/gotosocial/pull/812, so I'd rather get that merged first then adapt the discussion mentioned here in a new PR

**Comment by tsmethurst** [comment]
Alright, sounds good! 😊

Sent from ProtonMail mobile

-------- Original Message --------

**Pull request closed without merging**
