### PR TITLE
[chore] Bump ncruces/go-sqlite3 to 0.17.1

### PR DESCRIPTION
**Pull request by daenney**
# Description

More linkanme fixes.

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [ ] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [ ] I/we have performed a self-review of added code.
- [ ] I/we have written code that is legible and maintainable by others.
- [ ] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [ ] I/we have run tests and they pass locally with the changes.
- [ ] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by daenney** [comment]
Not sure I get the lint error. I can build just fine.

**Comment by tsmethurst** [comment]
Hmrnm, I'm not sure either... Did the required go version change or something?

**Comment by ncruces** [comment]
There seems to be a new file missing from your vendored copy:
https://github.com/ncruces/go-sqlite3/blob/main/registry.go

This has the missing `initExtensions` function. Maybe you have it locally but didn't add it to git?

**Comment by daenney** [comment]
```
~/D/g/g/gotosocial ❯❯❯ git status                               upgrade-sqlite ◼
On branch upgrade-sqlite
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	vendor/github.com/ncruces/go-sqlite3/registry.go
```

:facepalm:

**Comment by daenney** [comment]
I ran `go mod vendor` but forgot to add it.

**Comment by tsmethurst** [comment]
Whoops! :D

**Pull request merged**
