### PR TITLE
Feature: tag timeline

### PR DESCRIPTION
**Pull request by leopku**

### CODE REVIEW

**Comment by tsmethurst** [comment]
This looks great so far! Just tag a couple of us for review when you're ready (i see you still have a few things in progress). Thanks so much for your hard work!

**Comment by leopku** [comment]
> This looks great so far! Just tag a couple of us for review when you're ready (i see you still have a few things in progress). Thanks so much for your hard work!

Thank you and thanks for your awesome open source project.

Because I'm so new to this project and did not dive into this project, this PR maybe needs some code review before it can be accepted.

**Comment by tsmethurst** [comment]
> this PR maybe needs some code review before it can be accepted.

no problem! I'll try and find time this weekend to have a look through and give you some feedback :)

**Comment by tsmethurst** [comment]
Heya! I just did some big config/CLI retooling on the main branch. Can you rebase this from main? Then I'll have a look at it :) Sorry for the inconvenience!

**Comment by leopku** [comment]
> Heya! I just did some big config/CLI retooling on the main branch. Can you rebase this from main? Then I'll have a look at it :) Sorry for the inconvenience!

No problem. I will push it again after rebasing.

**Comment by leopku** [comment]
It was done.

**Comment by tsmethurst** [comment]
Heya, I started having a look through, and I can see why you were running into trouble with it: some of the code that's left over in the database interface (the `TagStringsToTags` function in particular) is really *old* code which needs to be rewritten and cleaned up, because it's a mess right now. I think it might be best to leave this PR open for now and I'll ping you when some of the tag code is cleaned up. What do you think?

**Comment by leopku** [comment]
> Heya, I started having a look through, and I can see why you were running into trouble with it: some of the code that's left over in the database interface (the `TagStringsToTags` function in particular) is really _old_ code which needs to be rewritten and cleaned up, because it's a mess right now. I think it might be best to leave this PR open for now and I'll ping you when some of the tag code is cleaned up. What do you think?
> 
> [edit] sorry for taking so long to get back to you!

It's okay. Thanks for your review.

**Comment by tsmethurst** [comment]
> It's okay. Thanks for your review.

No problem! Sorry we couldn't get it merged right away. As soon as I get around to fixing the surrounding code I'll let you know :)

**Comment by tsmethurst** [comment]
Heya, unfortunately we still haven't got around to implementing tag logic yet (it's currently on the roadmap for some time in the next couple months) and this PR has fallen behind main quite a lot since it was opened, so I'm going to close it. If you want to have another crack at it soon with a fresh PR you're very welcome. I'm sorry we couldn't get this merged

**Pull request closed without merging**
