### PR TITLE
[docs] Add Repology stats

### PR DESCRIPTION
**Pull request by daenney**
# Description

Instead of a manually curated list of distribution packages, this adds the Repology[1] widget instead.

This also separates out the distribution packages from the self-hosting/deployment options into their own sections.

[1]: https://repology.org/project/gotosocial/versions

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [ ] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [ ] I/we have performed a self-review of added code.
- [ ] I/we have written code that is legible and maintainable by others.
- [ ] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [ ] I/we have run tests and they pass locally with the changes.
- [ ] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by daenney** [comment]
This is an alternative to #1852

**Comment by daenney** [comment]
https://gotosocial--1859.org.readthedocs.build/en/1859/installation_guide/third_party/

**Comment by tsmethurst** [comment]
Oh neat :) thanks! Could you add this widget to the readme as well?

**Comment by daenney** [comment]
Done! Also added the Helm chart from the README to the docs

**Pull request merged**
