### PR TITLE
[feature] Add healthcheck endpoints `/livez` and `/readyz`

### PR DESCRIPTION
**Pull request by tsmethurst**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

This pull request adds some simple health check endpoints, and documentation for how to configure a health check.

Closes https://github.com/superseriousbusiness/gotosocial/issues/2707

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by NyaaaWhatsUpDoc** [comment]
this otherwise looks good and ready to go, but just one question: would it be worth instead doing a database ping instead of an actual select on a table? or instead just do a select on a table with no columns (just so we don't end up doing any actual searching)

**Comment by tsmethurst** [comment]
Mm, the nice thing about doing a little select instead of a ping is that I don't think pinging catches things like database locked etc. Actually selecting something is a bit more of a representative test of "is this thing on", imo.

> or instead just do a select on a table with no columns (just so we don't end up doing any actual searching).

I'd be happy to change it to that yeah, like just a `SELECT * [...] LIMIT 1` you mean? Is that cheaper?

**Comment by NyaaaWhatsUpDoc** [comment]
> Mm, the nice thing about doing a little select instead of a ping is that I don't think pinging catches things like database locked etc. Actually selecting something is a bit more of a representative test of "is this thing on", imo.
> 
> > or instead just do a select on a table with no columns (just so we don't end up doing any actual searching).
> 
> I'd be happy to change it to that yeah, like just a `SELECT * [...] LIMIT 1` you mean? Is that cheaper?

no i mean you can write a statement that basically returns just none of the columns, so for example here's:
```
sqlite> select null from instances limit 0;
Run Time: real 0.000 user 0.000075 sys 0.000000
```

and then compared to the original:
```
sqlite> select id from instances where domain = "k.iim.gay";
01A0XSYN1D4BG83VMGPEV17PH2
Run Time: real 0.000 user 0.000177 sys 0.000000
```

not a huge difference given they're both absurdly fast, but there is *some*

**Comment by tsmethurst** [comment]
Got it! Changed it here https://github.com/superseriousbusiness/gotosocial/pull/2783/commits/49247130c482fea652d6debba28e8623b17552d0 and it seems to work for both sqlite and postgres :)

**Pull request merged**
