### PR TITLE
[feature/frontend] Allow setting alt-text for avatar + header

### PR DESCRIPTION
**Pull request by tsmethurst**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

This PR allows users to set alt text on their headers + avatars, which will then show up on the web frontend for their profile (falls back to previous alt text if no alt text set).

Also uses a photoswipe gallery view for the avatar in the profile header, so it can be peeped at more closely without having to open another tab (falls back to previous behavior if no javascript allowed on page).

Alt text isn't federated at this point, it's just stored locally.

closes https://github.com/superseriousbusiness/gotosocial/issues/75

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
Is the header/avatar alt text federated at all?

**Comment by tsmethurst** [comment]
Not yet! Some time soon we'll probably start federating it in the title or summary or whatever it is that's used for attachments currently, should be a relatively small change I think.

**Comment by ThisIsMissEm** [comment]
Alright, because just the other night I was thinking about "do we have alt text for these?" and realised we didn't in Mastodon. (we apparently use the "name" property for alt text)

**Comment by ThisIsMissEm** [comment]
We currently use `name` but are discussing using `summary` (which we also prefer in versions greater than 3.2.0 for media attachments), however there is a concern about `summary` being able to contain HTML, and hence needing to be sanitised.

Hopefully we'll also support sending both for at least one minor relesse.

https://github.com/mastodon/mastodon/pull/32538

We've also marked implementation of alt text on avatars & headers as a "help wanted" ticket, which means that the team wants to implement, it's small enough that someone could implement with guidance, and guidance/help will be provided.

https://github.com/mastodon/mastodon/issues/10313#issuecomment-2416000335

**Comment by tsmethurst** [comment]
That's great, thanks for the updates :) I'll make an issue for GtS specifically to federate these fields out, and link back here.

**Pull request merged**
