### PR TITLE
[docs] Revamp the installation guide

### PR DESCRIPTION
**Pull request by daenney**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

This tries to revamp/restructure the installation guide. It's renamed to "Getting Started" as it now contains a few more things than just the installation, especially the deployment considerations which we didn't use to spell out as much ahead of time.

Installation is now a section with the guides on their own and I did the same for reverse proxies. I've removed a bit of redundancy like the user creation. I also removed the rogue reverse proxy section in the Docker guide and lifted that into the reverse proxy section.

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [ ] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [ ] I/we have performed a self-review of added code.
- [ ] I/we have written code that is legible and maintainable by others.
- [ ] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [ ] I/we have run tests and they pass locally with the changes.
- [ ] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by daenney** [comment]
I have some ideas on how to rewrite the installation guides themselves too to hopefully make them a bit more approachable. But that's a separate thing and this was already getting quite big.

**Comment by daenney** [comment]
https://gotosocial--1877.org.readthedocs.build/en/1877/ shows the docs as created by this PR.

**Review by decentral1se — APPROVED** [review]

**Comment by tsmethurst** [comment]
Excellent! Thank you! This was much needed. Could you resolve the conflict? Then I'll merge this :)

**Comment by daenney** [comment]
Git got confused over some file path moves when I tried to rebase so I rewrote the commit. But same as before, just with the tracing thing in the user guide now too.

**Pull request merged**
