### PR TITLE
[feature] Support OTLP HTTP, drop Jaeger

### PR DESCRIPTION
**Pull request by daenney**
# Description

Jaeger supports ingesting traces using the OpenTelemetry gRPC or HTTP methods. The Jaeger project has deprecated the old jaeger transport.
    
* Add support for submitting traces over HTTP
* Drop support for the old Jaeger protocol
* Upgrade the trace libraries to v1.17
    
Fixes: #2176
Fixes: #2179

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [ ] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by tsmethurst** [comment]
Code looks good to me. I don't use tracing myself, but if you've tested it and it works OK for you then feel free to squerge :)

**Comment by daenney** [comment]
I use the gRPC one, which continues to work. I'll see if I can find an easy way to test the HTTP transport locally.

**Comment by daenney** [comment]
Alright, everything works but had to slightly fix the docs. We shouldn't be included the protocol even for the HTTP endpoint.

**Comment by daenney** [comment]
One thing is that even though the transport is called `http`, it'll use HTTPS unless `tracing-insecure-transport` is `true`. We could in theory have http and https transports, or parse the endpoint instead and figure it out from there. But this keeps the symmetry with the gRPC endpoint.

**Pull request merged**
