### PR TITLE
[bugfix] Fix dereferencing ancestors on new status create

### PR DESCRIPTION
**Pull request by tsmethurst**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

Likely fix for https://github.com/superseriousbusiness/gotosocial/issues/2460.

Looks like on new status creates, we were passing the "barebones" status into the dereferenceThread function, which did not include the correct inReplyToURI values. This should fix it by passing in the properly dereferenced and populated status instead.

As a result of this fix, more followers-only posts were showing up in the timeline, even when the post they reply to is not visible. This PR fixes that too, by not assuming that 404 always means deleted when trying to deref a status. Many implementations (including Mastodon) just return 404 when we don't have permission to view a status because of its visibility settings, so we need to take account of that by leaving the in_reply_to_uri in place in such cases for visibility filtering purposes.

The PR also tones down the "status not deref'd" warnings to debug level instead, since they represent a legitimate state that GtS can and will end up in when checking visibility.

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [x] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by daenney** [comment]
I've plonked it on my instance too. I'll keep an eye out. There's a few people who seem to manage to provoke broken threads somewhat regularly as they like to chain-post a lot.

**Comment by NyaaaWhatsUpDoc** [comment]
this definitely won't fix *all* situations. some broken threads occur due to failed fetched at which point it should be picked up by the visibility filter, these i'm fixing in a separate patch i'm working on as previously mentioned in the matrix. but this fix here should absolutely fix a bunch of situations given we're not passing in the latest dereferenced / stored status :woman_facepalming:

**Comment by tsmethurst** [comment]
I have found another issue with this now, which is that lots of followers-only replies by people you do follow are showing up in the timeline, but they respond to followers-only posts by people you don't follow. I've found where the problem is and I'll fix it a tomorrow or Monday.

**Comment by tsmethurst** [comment]
But yes, it already seems better :)

**Pull request merged**
