### PR TITLE
[Feature] Add global instance CSS customization setting

### LINKED ISSUE #3348: [feature] Add custom CSS for Instance Frontpage
### Is your feature request related to a problem ?

You're able to add custom CSS for individual profiles but not for the instance front page itself.

### Describe the solution you'd like.

Implement a custom CSS field in the instance settings that works the same way as the custom CSS for profiles but that affects the front page.

This would also change the CSS for the `/about` and `/signup` page or any other instance related pages. Excluding the dashboard

### Describe alternatives you've considered.

Instance admins could potentially do this by manually editing the provided CSS files. However, it's not everyone who's comfortable doing  this. and a built-in setting would be more fun and accessible.

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by S0yKaf**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

Allow instance admins to add custom CSS that will affect every page of their instance.

This is done with a new CustomCSS instance setting that works pretty much exactly like the Users CustomCSS property. This custom CSS is then requested for every page load. User styles/themes take precedence over this CSS.

closes #3348

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [ ] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by S0yKaf** [comment]
Contrary to what I've said in the Issue, this will also affect the CSS in the dashboard. Again, no stress for the review, I know you're all busy with the 0.17 release.

**Comment by S0yKaf** [comment]
```
[GIN-debug] GET    /                         --> github.com/superseriousbusiness/gotosocial/internal/middleware_test.testHeaderFilter.func1 (2 handlers)
--- FAIL: TestThrottlingMiddleware (3.22s)
    throttling_test.go:100: did not return status 429 (200) with queueLimit=512 and request=530
FAIL
FAIL	github.com/superseriousbusiness/gotosocial/internal/middleware	15.506s
ok  	github.com/superseriousbusiness/gotosocial/internal/oauth	5.872s
ok  	github.com/superseriousbusiness/gotosocial/internal/paging	0.053s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing	16.454s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/account	58.451s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/admin	47.852s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/conversations	22.749s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/interactionrequests	13.797s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/media	21.014s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/polls	6.387s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/status	30.041s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/stream	6.448s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/timeline	7.412s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/user	8.663s
ok  	github.com/superseriousbusiness/gotosocial/internal/processing/workers	163.601s
ok  	github.com/superseriousbusiness/gotosocial/internal/router	0.047s
ok  	github.com/superseriousbusiness/gotosocial/internal/text	83.479s
ok  	github.com/superseriousbusiness/gotosocial/internal/timeline	36.871s
ok  	github.com/superseriousbusiness/gotosocial/internal/trans	6.882s
ok  	github.com/superseriousbusiness/gotosocial/internal/transport	19.790s
ok  	github.com/superseriousbusiness/gotosocial/internal/transport/delivery	(cached)
ok  	github.com/superseriousbusiness/gotosocial/internal/typeutils	115.179s
ok  	github.com/superseriousbusiness/gotosocial/internal/util	0.809s
ok  	github.com/superseriousbusiness/gotosocial/internal/validate	0.022s
FAIL
```

This is what's failing the tests but I can't seem to be able to reproduce it locally. Thoughts?

**Comment by tsmethurst** [comment]
Yes, just a flaky test I think, I'll re-run

**Comment by tsmethurst** [comment]
Great stuff, thank you! Sorry for the late review :') I'll get this branch up to date and squerge it.

**Comment by S0yKaf** [comment]
Hey cool, Thank you!

**Pull request merged**
