### PR TITLE
[feature] Implement preferences client API

### PR DESCRIPTION
**Pull request by daenney**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

This adds the preferences endpoint to our Mastodon Client API implementation. It's a read-only endpoint that returns a number of user preferences. Applications can query these settings when logging in a user (for the first time) to configure themselves.

This came up during a debug session with @natsukagami in the help channel. Elk.zone has started using this endpoint but wasn't handling the absence of it. Elk has been updated to deal with that, but this seems useful enough to expose in general.

Relates to: https://github.com/elk-zone/elk/pull/2069

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [x] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by daenney** [comment]
So the additional Swagger gen changes look a bit... odd? Like it doesn't feel those should be there but I added them in the PR in case someone knows what's up. But I think I should drop that commit?

**Comment by tsmethurst** [comment]
> So the additional Swagger gen changes look a bit... odd? Like it doesn't feel those should be there but I added them in the PR in case someone knows what's up. But I think I should drop that commit?

Yeah, I'm not sure what's going on there.... some change in the latest version of go swagger?

here's the version the ci/cd is currently using:

```
version: v0.30.4
commit: (unknown, mod sum: "h1:cPrWLSXY6ZdcgfRicOj0lANg72TkTHz6uv/OlUdzO5U=")
```

and the command for generating the docs:

```
swagger generate spec --scan-models --exclude-deps -o docs/api/swagger.yaml
```

**Comment by daenney** [comment]
Ah, I might've forgotten about `--exclude-deps`, that would explain the extra diff I think. I'll try and rerun that again.

**Comment by daenney** [comment]
Yup so adding `--exclude-deps` caused the extra diff to disappear. I've dropped the commit now

**Pull request merged**
