### PR TITLE
Create login.md and log in from toot CLI client

### PR DESCRIPTION
**Pull request by xmgz**
as many people fail to set up _toot cli_ client, I've this detailed guide about login and clients so any can reference to. It's adapted from my blog post and of course feel free to adapt and/or correct to the community guides and styling.

I can not upload images to `assets` so I linked to my blog

I hope it's useful.

### CODE REVIEW

**Comment by tsmethurst** [comment]
Aha, the PR is appreciated, thank you! Unfortunately it's already a little out of date: we recently merged https://github.com/superseriousbusiness/gotosocial/pull/889 so that users no longer need to look in their network requests for the token. This makes logging in with toot CLI and other such clients much much simpler, so I'm not sure if this extra documentation will be necessary :thinking:

**Comment by xmgz** [comment]
LOL thank you!  

Do what you consider best for the users :wink: 

You can keep this PR opened, keep the first part and then just edit (or delete) the `toot cli` part when the new login code is been published.

Thanks anyway for your work :sloth:

**Comment by tsmethurst** [comment]
Sorry for the delay! Was working on something else and then got sick for a while. If it's OK with you I'm gonna close this, and then lift parts out of it later when adding further documentation. Will credit you then :) lmk if that sounds reasonable to you!

**Comment by xmgz** [comment]
Agree. Thank you.

**Pull request closed without merging**
