### PR TITLE
[bugfix] set the memory limit for ncruces/go-sqlite3 according to 32 / 64 bit platform

### PR DESCRIPTION
**Pull request by NyaaaWhatsUpDoc**
This sets the WebAssembly runtime memory limit for ncruces/go-sqlite3 according to it being a 32 / 64 bit platform. This should help in the cases of https://github.com/ncruces/go-sqlite3/issues/168#issuecomment-2412429221 also just means we don't end up over-reserving memory when we don't need to.

This also raises the question of what we can do about ffmpeg in the future, but we'll need to do some serious testing to figure out exactly what limit we can set that won't cause things to blow up :')

### CODE REVIEW

**Comment by tsmethurst** [comment]
Grand! Let's merge this after 0.17.0 is out, so we can test it for a bit longer and then do 0.17.1 if necessary.

**Comment by ncruces** [comment]
You may find [`bits.UintSize`](https://pkg.go.dev/math/bits#pkg-constants) more readable.

**Comment by ncruces** [comment]
If you want to wait for 0.17.1, I'll probably merge https://github.com/ncruces/go-sqlite3/pull/170 by then.

I hate how huge and confusing my `//go:build` lines are becoming, but this is a better default configuration, and WAL seems to work fine with `386` and  `arm` (although the interpreter will be slower than modernc for many use cases).

**Comment by ncruces** [comment]
I consider this a "compatibility" change, so ti will be a `v1.20.0`.

I had planed to release it ["today"](https://github.com/ncruces/go-sqlite3/issues/175), but I'm a bit [stuck](https://github.com/ncruces/go-sqlite3/issues/172).

I doubt that the "compatibility" breaks will be an issue to anyone, but since they're there, I'd rather bundle them together, in a single release notes.

**Comment by ncruces** [comment]
See: https://github.com/ncruces/go-sqlite3/releases/tag/v0.20.0

**Pull request closed without merging**
