### PR TITLE
docs: local docs hacking howto

### PR DESCRIPTION
**Pull request by decentral1se**
# Description

HOWTO on how to set things up locally for docs hacking.

Alternatively, we could commit a `requirements.txt` to root so that folks can `pip install -r requirements.txt` and maintainers can `pip freeze > requirements.txt` when things get updated / added. Happy to re-work this PR with that change if desired.

> [Rendered](https://github.com/decentral1se/gotosocial/blob/65b328c075c3336e36f3301cc87105a7909087c2/CONTRIBUTING.md)

This is my `requirements.txt` atm:

```
beautifulsoup4==4.12.2
cairocffi==1.5.1
CairoSVG==2.7.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
cssselect2==0.7.0
defusedxml==0.7.1
ghp-import==2.1.0
idna==3.4
importlib-metadata==6.6.0
Jinja2==3.1.2
Markdown==3.3.7
MarkupSafe==2.1.2
mergedeep==1.3.4
mkdocs==1.4.3
mkdocs-material==9.1.14
mkdocs-material-extensions==1.1.1
mkdocs-swagger-ui-tag==0.6.1
packaging==23.1
Pillow==9.5.0
pycparser==2.21
Pygments==2.15.1
pymdown-extensions==10.0.1
python-dateutil==2.8.2
PyYAML==6.0
pyyaml-env-tag==0.1
regex==2023.5.5
requests==2.31.0
six==1.16.0
soupsieve==2.4.1
tinycss2==1.2.1
urllib3==2.0.2
watchdog==3.0.0
webencodings==0.5.1
zipp==3.15.0
```

## Checklist

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by decentral1se** [comment]
CI failure seems unrelated?

> https://drone.superseriousbusiness.org/superseriousbusiness/gotosocial/6019/1/3

**Comment by tsmethurst** [comment]
> CI failure seems unrelated?
> 
> > https://drone.superseriousbusiness.org/superseriousbusiness/gotosocial/6019/1/3

Yeah, there's an issue with one of our tests, it's unrelated indeed :)

**Comment by tsmethurst** [comment]
Aha, we already have the conda equivalent of a requirements.txt for this!

https://github.com/superseriousbusiness/gotosocial/blob/main/docs/environment.yml

So the steps here are:

1. install miniconda (https://docs.conda.io/en/latest/miniconda.html)
2. create your conda environment by doing `conda env create -f ./docs/environment.yml`
3. activate conda environment: `conda activate gotosocial-docs`
4. `mkdocs serve`

Adding instructions for setting up the docs with miniconda is easier, I think, than maintaining a separate environment.yml and requirements.txt, so that would be my preference. What do you think?

**Comment by decentral1se** [comment]
@tsmethurst aha, I see. thanks for pointing that one out. I don't use Conda myself but I could adapt the PR to show both approaches? I know it might be a bit of a spiral into Python packaging dungeons also... but I guess there will be "only pip" users coming by to hack docs at some point too... there seems to be a couple of ways to plug the `.yml` into the `.txt` by referencing each other over [here](https://stackoverflow.com/questions/35245401/combining-conda-environment-yml-with-pip-requirements-txt). up to you!

**Comment by daenney** [comment]
We removed `requirements.txt` a while ago. We build the docs using Conda and that's what RTD is configured to use too. We've run into some problems before with that and keeping those two in sync is frustrating.

I would suggest for any documentation we show how to use it through Conda and leave pip/requirements.txt out of it. Ultimately, that's also what CI will be using and how RTD will be building.

**Comment by decentral1se** [comment]
Cool, I can adjust the docs to support Conda as The Blessed Way. I can add a note to say "check that `docs/environment.yml` for the dependencies if you don't use Conda" with an incomplete example and folks can figure it out.

**Comment by decentral1se** [comment]
New commit is there, [rendered version](https://github.com/superseriousbusiness/gotosocial/blob/f10c9ed9386c600d9cc680eefc7fd5de881b810a/CONTRIBUTING.md#documentation).

**Comment by tsmethurst** [comment]
Thanks! :)

**Pull request merged**
