### PR TITLE
handle db-url

### PR DESCRIPTION
**Pull request by winston0410**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
For https://github.com/superseriousbusiness/gotosocial/issues/3172

This PR implemented a new field in configuration called `db-url`. This allow user to defined their connection to database using DSN, so they can customize the database behavior as much as they want. For example, they can allow connection to DB with schema using the following URL:

```yaml
db-url: 'postgres://user:pass@localhost/db?search_path=gotosocial'
```

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [x] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by winston0410** [comment]
Hi @tsmethurst , do you mind reviewing this for me please?

**Comment by tsmethurst** [comment]
Hmm I think I'd rather we called this `db-postgres-connection-string`, and put it after the `db-sqlite-*` options in the config, just to emphasize that it's an advanced option and specific to PG. Could you make those changes? Aside from that this looks good to me I think :)

**Comment by winston0410** [comment]
@tsmethurst no problem, I have changed from `db-url` to `db-postgres-connection-string` now. Can you review this again?

**Comment by tsmethurst** [comment]
Looks good, thank you!

**Pull request merged**
