### PR TITLE
[feature] About page

### PR DESCRIPTION
**Pull request by f0x52**
# Description
Basic /about page, using the full instance description and generating some more info from various settings. Also links to `/about/suspended` if enabled.

image

## Checklist

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [ ] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by f0x52** [comment]
I think this will serve as a decent base combining the editable long description with some auto-generated info about the settings, but should be override-able when we get more generic 'instance pages' support (https://github.com/superseriousbusiness/gotosocial/issues/881)

**Comment by f0x52** [comment]
something to fix: custom emoji are displayed way too big in the contact card :")
image

**Comment by tsmethurst** [comment]
Should i merge this now and we can fix the emoji stuff in a separate patch? or do you wanna do it in this PR?

**Comment by f0x52** [comment]
might as well wait with merging till it's fixed I think, should be soon(tm)

**Comment by xmgz** [comment]
Excuse me, may I propose an enhacement here? I think it's the right place.

wouldn't it be good have a direct link to "/about" in the profile/user-TL page footer? As it happens with "contact" and "instance version". Otherwise this **About** page is hidden without public links (as far as I'd seen) for casual visitiors.

Having **markdown** for the long instance description would also help, adding some formatting. In my opinion.

thank you.

**Pull request merged**
