### PR TITLE
[chore] Update usage of OTEL libraries

### PR DESCRIPTION
**Pull request by daenney**
# Description

This updates all the OTEL libraries to latest, which we can now do thanks to @milas fix in #2712.

Additionally:
* Applies the same fix to the metrics schema
* Adds the software version to the tracing schema

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [x] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by daenney** [comment]
@milas Would you mind taking a look? I can't imagine adding the software version would cause any trouble, but I'd love your input.

**Comment by daenney** [comment]
For reviewers, the first commit is just the dependency bump. You can skip that.

**Review by milas — APPROVED** [review]
This looks good to me - shouldn't be any resource conflicts

I'll build & test on my instance tonight to be sure though!

**Comment by daenney** [comment]
I'm going to merge this because the changes to `vendor/` can result in conflicts with other PRs and it's a bit tedious to fix. Please yell at me if it ends up broken on main.

**Pull request merged**
