### PR TITLE
[feature] Add metrics

### PR DESCRIPTION
**Pull request by daenney**
# Description

I'm opening this as a draft PR so I can tempt @NyaaaWhatsUpDoc :stuck_out_tongue:.

Current state:
* Instruments HTTP endpoints, haven't gotten around to the client yet
* I dislike magical global objects in prometheus like the default registry hence setting up an explicit one
* I've tried to find a way to make it as optional as possible and not load any machinery if metrics are not enabled
* There are probably better ways of doing and structuring this

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [ ] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [ ] I/we have performed a self-review of added code.
- [ ] I/we have written code that is legible and maintainable by others.
- [ ] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [ ] I/we have run tests and they pass locally with the changes.
- [ ] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by NyaaaWhatsUpDoc** [comment]
You have successfully tempted me... When I get time I'll try bring across my existing metrics changes :')

**Comment by daenney** [comment]
I put it "in production". You can see them at https://ap.dny.social/metrics.

I hadn't realised that `c.Request.Path` would include stuff like `/users/<username>`, that's going to do some cardinality explosion we want to avoid. I guess we could use `c.HandlerName()` instead? It would be nice if we could get a name like `/users/:id/inbox` instead.

**Comment by daenney** [comment]
One thing that's probably worth thinking about is whether we want to partition by endpoint and method. This creates a ton of timeseries and histograms are generally expensive to ingest and do math over. It's possible to use summaries instead but that means the compute cost is now on the client instead of the probably beefier Prometheus server.

I'm thinking having separate subsystems, like `clientapi`, `federation` etc. + partitioning by status code might be enough? That should give you an indication of where a problem might be in general and trace the rest through logs or proper tracing once we add that.

**Comment by daenney** [comment]
I took a peak at the Hachyderm public dashboard: https://grafana.hachyderm.io/public. One thing that's interesting there is they only surface HTTP GET/POST 200s for the federation endpoints. Maybe we actually want to do something similar since that's really the metric you're the most likely to be interested in, and bundle everything else in a histogram that doesn't split out by method and code?

**Comment by daenney** [comment]
I'm going to axe this PR for a bit. I've been looking around and there's an alternative way I want to try and do this directly through the OpenTelemetry metrics. That avoids needing to potentially migrate those over later and would put us close to being able to wire up tracing too.

I'll be tinkering around with this for the weekend. I'll probably fax a PR sometime in the week if I can get a complete demo up.

**Pull request closed without merging**
